package com.tangkikodo.kotlinresolve

import java.util.ServiceLoader
import kotlin.reflect.KClass

/**
 * Compile-time-generated zero-reflection accessor for one KotlinResolve model class.
 *
 * For each class with `@Resolve` / `@Post` methods, the `kotlin-resolve-ksp` processor
 * generates an adapter that calls methods and reads/writes fields directly — no
 * `Method.invoke`, no `KMutableProperty1.set`. When the KSP plugin is not applied, the
 * Resolver falls back to a reflective adapter built at runtime (see
 * [com.tangkikodo.kotlinresolve.metadata.scan]).
 */
interface KotlinResolveAdapter<T : Any> {
    /** Pre-computed metadata for the class. Built once at adapter init. */
    val meta: ResolveMeta

    /**
     * Invoke the @Resolve method at [methodIndex] (position in [meta.resolveMethods]).
     * Direct call: `node.resolveOwner(loader)`.
     */
    suspend fun invokeResolveMethod(node: T, methodIndex: Int, ctx: InvokeCtx): Any?

    /**
     * Invoke the @Post method at [methodIndex] (position in [meta.postMethods]).
     * Direct call: `node.postTaskCount(collector)`.
     */
    suspend fun invokePostMethod(node: T, methodIndex: Int, ctx: InvokeCtx): Any?

    /** Read field value by name. Used by ExposeAs / SendTo / object-field traversal. */
    fun readField(node: T, fieldName: String): Any?

    /** Write resolve/post result to field. Direct assignment: `node.owner = value`. */
    fun writeField(node: T, fieldName: String, value: Any?)

    /** Snapshot of (fieldName, value) for every object field on [node]. */
    fun collectObjectFields(node: T): List<Pair<String, Any?>>
}

/**
 * Bag of values supplied to a single resolve/post invocation. The adapter picks what
 * it needs by parameter name (matched at codegen time, so the runtime cost is just
 * field reads).
 */
class InvokeCtx(
    val loader: DataLoader<*, *>?,
    val parent: Any?,
    val context: Map<String, Any?>?,
    val ancestorContext: AncestorContext,
    val collectors: Array<ICollector<Any?>>,
)

/**
 * ServiceLoader hook generated by the KSP processor. One implementation per
 * compilation unit; returns the map of "class -> adapter" for everything that unit
 * processed.
 *
 * Returns Map<KClass<out Any>, KotlinResolveAdapter<out Any>> — type-erased to Any
 * to keep KotlinPoet generation simple. AdapterRegistry casts at lookup time.
 */
interface KotlinResolveAdapterFactory {
    fun create(): Map<KClass<out Any>, KotlinResolveAdapter<out Any>>
}

/**
 * Global registry. On JVM init, ServiceLoader discovers every factory on the
 * classpath and merges their maps. Lookup is a plain HashMap get — O(1).
 */
object AdapterRegistry {
    private val adapters: Map<KClass<*>, KotlinResolveAdapter<*>> = run {
        val merged = HashMap<KClass<*>, KotlinResolveAdapter<*>>()
        val loader = ServiceLoader.load(KotlinResolveAdapterFactory::class.java)
        for (factory in loader) {
            for ((kls, adapter) in factory.create()) {
                merged[kls] = adapter
            }
        }
        merged
    }

    @Suppress("UNCHECKED_CAST")
    fun <T : Any> get(kls: KClass<T>): KotlinResolveAdapter<T>? =
        adapters[kls] as? KotlinResolveAdapter<T>
}
